<!-- /* */ comments (C block comment) -->
<style name="comment" fore={comment-fore} />
<!-- // comments (C++ line comment) -->
<style name="commentline" fore={comment-fore} />
<!-- /** */ comments (asdoc/javadoc style C comment) -->
<style name="commentdoc" fore={commentdoc-fore} />
<!-- /// comments -->
<style name="commentlinedoc" fore={commentdoc-fore} />
<!-- asdoc/javadoc keywords in comments -->
<style name="commentdockeyword" fore={commentdockeyword-fore} />
<!-- invalid asdoc/javadoc keywords in comments -->
<style name="commentdockeyworderror" fore={commentdockeyword-fore} back={commentdockeyworderror-back} />
