<!--
	caret-fore - caret color
	caretline-back - caret line background
	selection-fore - selected text color
	selection-back - selected text background
	margin-fore - margin (code folding) background mix color 1
	margin-back - margin (code folding) background mix color 2
	marker-fore - code folding indicators fill color
	marker-back - code folding indicators line color
	highlight-back - quickfind bar highlight all semi-transparent background (if "Highlight all" checkbox is ticked)
	highlightword-back - highlight matching word semi-transparent background (if "Editor > Highlight Matching Words Mode" is enabled)
	modifiedline-back - modified line margin background (if "Display > View Modified Lines" option is true)
	colorize-marker-back - (true/false) colorize first margin column with 'gdefault' style foreground color
	bookmarkline-back - bookmark line background (if "Display > View Bookmarks" option is true)
	print-margin - print margin color (if "Editor > Print Margin Column" option is greater than 0)
	error line - (debugger) enabled breakpoint semi-transparent (if "Display > View Bookmarks" option is true, otherwise regular) background
	debug line - (debugger) current line semi-transparent background
	disabled line - (debugger) disabled breakpoint semi-transparent background
-->
<editor-style caret-fore={caret-fore} caretline-back={caretline-back} selection-fore={selection-fore} selection-back={selection-back} margin-fore={margin-fore} margin-back={margin-back} marker-fore={marker-fore} marker-back={marker-back} highlight-back={highlight-back} highlightword-back={highlightword-back} modifiedline-back={modifiedline-back} bookmarkline-back={bookmarkline-back} colorize-marker-back="true" />
