<!-- regular text -->
<style name="default" font={font-face} size={font-size} fore={default-fore} back={default-back} />
<!-- 	
	fore - first margin column (bookmark and breakpoint indicators) background (if colorize-marker-back editor style is set to "true")
	back - empty editor area background
-->
<style name="gdefault" fore={gdefault-fore} />
<!-- margin (line numbers) -->
<style name="linenumber" fore={linenumber-fore} />
<!-- matching brace -->
<style name="bracelight" fore={bracelight-fore} back={bracelight-back} bold="true" />
<!-- unmatched brace, seemingly irrelevant (unmatched braces are displayed with the default style and red curly underline) -->
<!--<style name="bracebad" fore={bracebad-fore} back={bracebad-back} bold="true" />-->
<!-- control characters (char codes from 0 to 31); font, size, bold, italics are used, but not the colors -->
<style name="controlchar" bold="true" />
<!-- block indent guides -->
<style name="indentguide" fore={indentguide-fore} />
