<!-- numeric literals -->
<style name="number" fore={number-fore} />
<!-- string literals enclosed in single quotes '' -->
<style name="character" fore={character-fore} />
<!-- string literals enclosed in double quotes "" -->
<style name="string" fore={string-fore} />
<!-- C# verbatim string literals (e.g. @"unescaped \n (backslash n)"), seemingly disabled -->
<style name="verbatim" fore={verbatim-fore} />
<!-- unterminated string literal (e.g. "no closing quote) -->
<style name="stringeol" fore={stringeol-fore} />
<!-- literal regular expressions -->
<style name="regex" fore={regex-fore} />
<!-- IDL UUID, seemingly disabled -->
<style name="uuid" fore={uuid-fore} />
<!-- preprocessor directives starting with a hash # -->
<style name="preprocessor" fore={preprocessor-fore} />
<!-- operators -->
<style name="operator" fore={operator-fore} />
<!-- identifier (variables, functions, classes) -->
<style name="identifier" fore={identifier-fore} />
<!-- primary keywords (class extends implements import interface new case do while else if for in switch throw get set function var try catch finally while with default break continue delete return each const namespace package include use is as instanceof typeof) -->
<style name="globalclass" fore={globalclass-fore} />
<!-- additional keywords (AS3: void arguments Array Boolean Class Error Function int Math Number Object Event Timer XMLNode, etc.) -->
<style name="word" fore={word-fore} />
<!-- secondary keywords (AS3: true false NaN Infinity null undefined) -->
<style name="word2" fore={word2-fore} />
