<!-- additional keywords 3 (AS3: dynamic private public static intrinsic internal native override protected AS3 final) -->
<style name="word3" fore={word3-fore} />
<!-- additional keywords 4 (AS3 - disabled: trace addEventListener removeEventListener hasListener addChild addChildAt removeChild removeChildAt) -->
<!--<style name="word4" fore={word4-fore} />-->
<!-- additional keywords 5 (AS3: super this) -->
<style name="word5" fore={word5-fore} />
